apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-w8xg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-w8xg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-w8xg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-w8xg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-w8xg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tkzw-tenant/rhtap-demo-app/hacbs-test-project-w8xg@sha256:56b26f8df41df362727b9afb59d4011920959bfb35e67d752306e3ba93249218
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
