apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-w8xg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-tkzw-tenant/rhtap-demo-app/hacbs-test-project-w8xg@sha256:56b26f8df41df362727b9afb59d4011920959bfb35e67d752306e3ba93249218
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
